name: gargantext
version: '0.1.0.0'
synopsis: Deep (Collaborative) Text mining project
description: Please see README.md
category: Data
author: Gargantext Team
maintainer: team@gargantext.org
copyright:
    - ! 'Copyright: (c) 2017-2018: see git logs and README'
license: BSD3
homepage: https://gargantext.org
ghc-options: -Wall
dependencies:
- extra
- text
library:
  source-dirs: src
  default-extensions: 
  - NoImplicitPrelude
  ghc-options:
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Werror
  exposed-modules:
  - Gargantext
  - Gargantext.Analysis
  - Gargantext.DSL
  - Gargantext.Database
  - Gargantext.Database.Instances
  - Gargantext.Database.Ngram
  - Gargantext.Database.Node
  - Gargantext.Database.Facet
  - Gargantext.Database.NodeNgram
  - Gargantext.Database.NodeNgramNgram
  - Gargantext.Database.NodeNode
  - Gargantext.Database.NodeNodeNgram
  - Gargantext.Database.Utils
  - Gargantext.Database.User
  - Gargantext.Ngrams
  - Gargantext.Ngrams.Count
  - Gargantext.Ngrams.CoreNLP
  - Gargantext.Ngrams.Parser
  - Gargantext.Ngrams.Lang.En
  - Gargantext.Ngrams.Lang.Fr
  - Gargantext.Ngrams.Metrics
  - Gargantext.Ngrams.TextMining
  - Gargantext.Ngrams.Occurrences
  - Gargantext.Parsers
  - Gargantext.Parsers.WOS
  - Gargantext.Parsers.Date
  - Gargantext.Prelude
  - Gargantext.RCT
  - Gargantext.API
  - Gargantext.API.Auth
  - Gargantext.Types
  - Gargantext.Types.Main
  - Gargantext.Types.Node
  - Gargantext.Utils.DateUtils
  - Gargantext.Utils.Prefix
  dependencies:
  - base >=4.7 && <5
  - aeson
  - aeson-lens
  - attoparsec
  - async
  - base16-bytestring
  - bytestring
  - case-insensitive
  - containers
  - contravariant
  - conduit
  - conduit-extra
  - directory
  - duckling
  - filepath
  - http-conduit
  - ini
  - lens
  - logging-effect
  - opaleye
  - path
  - parsec
  - postgresql-simple
  - pretty
  - product-profunctors
  - profunctors
  - protolude
  - pureMD5
  - regex-compat
  - safe
  - semigroups
  - servant
  - servant-client
  - servant-multipart
  - servant-server
  - servant-auth
  - split
  - tagsoup
  - text-metrics
#  - utc
  - time
  - timezone-series
  - time-locale-compat
  - transformers
  - unordered-containers
  - uuid
  - vector
  - wai
  - warp
  - yaml
  - zlib
  - zip
  - path-io

executable:
  main: Main.hs
  source-dirs:      app
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N -O2
  dependencies:
    - gargantext
    - ini
    - base
    - unordered-containers

tests:
  garg-test:
    main: Main.hs
    source-dirs: src-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - gargantext
    - hspec
    - QuickCheck
  garg-doctest:
    main: Main.hs
    source-dirs: src-doctest
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - Glob
    - QuickCheck
    - base
    - gargantext
