name: gargantext
version: '0.1.0.0'
synopsis: Deep (Collaborative) Text mining project
description: Please see README.md
category: Data
author: Gargantext Team
maintainer: team@gargantext.org
copyright:
    - ! 'Copyright: (c) 2017-2018: see git logs and README'
license: BSD3
homepage: https://gargantext.org
ghc-options: -Wall
dependencies:
- extra
- text
library:
  source-dirs: src
  ghc-options:
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-signatures
  - -Wunused-binds
  - -Wunused-imports
  - -Werror
  exposed-modules:
  - Gargantext
  - Gargantext.API
  - Gargantext.Core
  - Gargantext.Core.Types
  - Gargantext.Prelude
  - Gargantext.Text
  - Gargantext.Text.Context
  - Gargantext.Text.List.CSV
  - Gargantext.Text.Metrics.Count
  - Gargantext.Text.Parsers.CSV
  - Gargantext.Text.Search
  - Gargantext.Text.Terms
  - Gargantext.Text.Terms.WithList
  - Gargantext.TextFlow
  - Gargantext.Viz.Graph.Distances.Matrice
  dependencies:
  - QuickCheck
  - accelerate
  - aeson
  - aeson-lens
  - aeson-pretty
  - async
  - attoparsec
  - base >=4.7 && <5
  - base16-bytestring
  - bytestring
  - case-insensitive
  - cassava
  - clustering-louvain
  - conduit
  - conduit-extra
  - containers
  - contravariant
  - data-time-segment
  - directory
  - duckling
  - exceptions
  - filepath
  - fullstop
  - fclabels
  - fast-logger
  - full-text-search
  - http-client
  - http-client-tls
  - http-conduit
  - http-api-data
  - http-types
  - hxt
  - hlcm
  - ini
  - jose-jwt
  - kmeans-vector
  - KMP
  - lens
  - logging-effect
  - matrix
  - monad-logger
  - mtl
  - natural-transformation
  - opaleye
  - parsec
  - path
  - path-io
  - postgresql-simple
  - pretty
  - product-profunctors
  - profunctors
  - protolude
  - pureMD5
  - regex-compat
  - resourcet
  - safe
  - semigroups
  - servant
  - servant-auth
  - servant-client
  - servant-job
  - servant-mock
  - servant-multipart
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - servant-static-th
  - split
  - stemmer
  - string-conversions
  - swagger2
  - tagsoup
  - text-metrics
  - time
  - time-locale-compat
  - timezone-series
  - transformers
  - transformers-base
  - unordered-containers
  - uuid
  - vector
  - wai
  - wai-cors
  - wai-extra
  - warp
  - yaml
  - zip
  - zlib
#  - utc

executables:
  gargantext-server:
    main: Main.hs
    source-dirs: bin/gargantext-server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - base
      - containers
      - gargantext
      - vector
      - cassava
      - ini
      - optparse-generic
      - unordered-containers
      - full-text-search

  gargantext-cli:
    main: Main.hs
    source-dirs: bin/gargantext-cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - aeson
      - async
      - base
      - bytestring
      - containers
      - gargantext
      - vector
      - cassava
      - ini
      - optparse-generic
      - split
      - unordered-containers
      - full-text-search

tests:
  garg-test:
    main: Main.hs
    source-dirs: src-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - gargantext
    - hspec
    - QuickCheck
    - quickcheck-instances 
    - time
    - parsec
    - duckling
    - text
  garg-doctest:
    main: Main.hs
    source-dirs: src-doctest
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wmissing-signatures
    dependencies:
    - doctest
    - Glob
    - QuickCheck
    - base
    - gargantext
