name: gargantext
version: '0.0.1.9.7'
synopsis: Search, map, share
description: Please see README.md
category: Data
author: Gargantext Team
maintainer: team@gargantext.org
copyright:
    - ! 'Copyright: (c) 2017-Present: see git logs and README'
license: AGPL-3
homepage: https://gargantext.org
ghc-options: -Wall
extra-libraries:
  - gfortran
dependencies:
  - extra
  - text
default-extensions:
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
library:
  source-dirs: src
  ghc-options:
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-signatures
  - -Wunused-binds
  - -Wunused-imports
  - -Werror
  - -freduction-depth=300
  exposed-modules:
  - Gargantext
  - Gargantext.API
  - Gargantext.API.Dev
  - Gargantext.API.HashedResponse
  - Gargantext.API.Node
  - Gargantext.API.Node.File
  - Gargantext.API.Ngrams
  - Gargantext.API.Ngrams.Types
  - Gargantext.API.Admin.Settings
  - Gargantext.API.Admin.Types
  - Gargantext.API.Prelude
  - Gargantext.Core
  - Gargantext.Core.Types
  - Gargantext.Core.Types.Individu
  - Gargantext.Core.Types.Main
  - Gargantext.Core.Utils.Prefix
  - Gargantext.Database.Action.Flow
  - Gargantext.Database.Query.Table.User
  - Gargantext.Database.Query.Table.Node
  - Gargantext.Database.Prelude
  - Gargantext.Database.Admin.Trigger.Init
  - Gargantext.Database.Admin.Config
  - Gargantext.Database.Admin.Types.Hyperdata
  - Gargantext.Database.Admin.Types.Node
  - Gargantext.Prelude
  - Gargantext.Prelude.Crypto.Pass.User
  - Gargantext.Prelude.Utils
  - Gargantext.Core.Text
  - Gargantext.Core.Text.Context
  - Gargantext.Core.Text.Corpus.Parsers
  - Gargantext.Core.Text.Corpus.Parsers.Date.Parsec
  - Gargantext.Core.Text.Corpus.API
  - Gargantext.Core.Text.Corpus.Parsers.CSV
  - Gargantext.Core.Text.Examples
  - Gargantext.Core.Text.List.CSV
  - Gargantext.Core.Text.Metrics
  - Gargantext.Core.Text.Metrics.TFICF
  - Gargantext.Core.Text.Metrics.CharByChar
  - Gargantext.Core.Text.Metrics.Count
  - Gargantext.Core.Text.Search
  - Gargantext.Core.Text.Terms
  - Gargantext.Core.Text.Terms.Mono
  - Gargantext.Core.Text.Terms.Multi.Lang.En
  - Gargantext.Core.Text.Terms.Multi.Lang.Fr
  - Gargantext.Core.Text.Terms.Multi.RAKE
  - Gargantext.Core.Text.Terms.WithList
  - Gargantext.Core.Text.Flow
  - Gargantext.Core.Viz.Graph
  - Gargantext.Core.Viz.Graph.Distances.Matrice
  - Gargantext.Core.Viz.Graph.Index
  - Gargantext.Core.Viz.Phylo
  - Gargantext.Core.Viz.AdaptativePhylo
  - Gargantext.Core.Viz.Phylo.PhyloMaker
  - Gargantext.Core.Viz.Phylo.Tools
  - Gargantext.Core.Viz.Phylo.PhyloTools
  - Gargantext.Core.Viz.Phylo.PhyloExport
  - Gargantext.Core.Viz.Phylo.SynchronicClustering
  - Gargantext.Core.Viz.Phylo.Example
  - Gargantext.Core.Viz.Phylo.LevelMaker
  - Gargantext.Core.Viz.Phylo.View.Export
  - Gargantext.Core.Viz.Phylo.View.ViewMaker
  - Gargantext.Core.Viz.Types
  dependencies:
  - HSvm
  - KMP
  - MonadRandom
  - QuickCheck
  - SHA
  - Unique
  - accelerate
  - aeson
  - aeson-lens
  - aeson-pretty
  - password
  - array
  - async
  - attoparsec
  - auto-update
  - base >=4.7 && <5
  - base16-bytestring
  - base64-bytestring
  - blaze-html
  - blaze-markup
  - blaze-svg
  - bytestring
  - case-insensitive
  - cassava
  - cereal     # (IGraph)
  - clock
  - clustering-louvain
  - conduit
  - conduit-extra
  - containers
  - contravariant
  - crawlerHAL
  - crawlerISTEX
  - crawlerIsidore
  - crawlerPubMed
  - data-time-segment
  - deepseq
  - directory
  - duckling
  - exceptions
  - fast-logger
  - fclabels
  - fgl
  - filelock
  - filepath
  - formatting
  - full-text-search
  - fullstop
  - graphviz
  - haskell-igraph
  - hlcm
  - hsparql
  - hstatistics
  - http-api-data
  - http-client
  - http-client-tls
  - http-conduit
  - http-media
  - http-types
  - hxt
  - ini
  - insert-ordered-containers
  - jose
  - json-stream
  - lens
  - located-base
  - logging-effect
  - matrix
  - MissingH
  - monad-control
  - monad-logger
  - mtl
  - natural-transformation
  - opaleye
  - pandoc
  - parallel
  - parsec
  - patches-class
  - patches-map
  - path
  - path-io
  - postgresql-simple
  - pretty-simple
  - probability
  - product-profunctors
  - profunctors
  - protolude
  - pureMD5
  - quickcheck-instances
  - rake
  - random
  - random-shuffle
  - rdf4h
  - regex-compat
  - resource-pool
  - resourcet
  - safe
  - semigroups
  - serialise
  - servant
  - servant-auth
  - servant-auth-server >= 0.4.4.0
  - servant-auth-swagger
  - servant-blaze
  - servant-cassava
  - servant-client
  - servant-job
  - servant-mock
  - servant-multipart
  - servant-server
  - servant-static-th
  - servant-swagger
  - servant-swagger-ui
  - servant-xml
  - simple-reflect
  - singletons # (IGraph)
  - template-haskell
  - wai-app-static

    # for mail
  - smtp-mail
  - mime-mail

    # for password generation
  - cprng-aes
  - binary
  - crypto-random

  - split
  - stemmer
  - string-conversions
  - swagger2
  - tagsoup
  - temporary
  - text-metrics
  - time
  - time-locale-compat
  - timezone-series
  - transformers
  - transformers-base
  - unordered-containers
  - uuid
  - validity
  - vector
  - wai
  - wai-cors
  - wai-extra
  - warp
  - wreq
  - xml-conduit
  - xml-types
  - xmlbf
  - yaml
  - zip
  - zlib
    #  - kmeans-vector
  #- charsetdetect-ae  # detect charset
#  - utc
#  API external connections

executables:
  gargantext-server:
    main: Main.hs
    source-dirs: bin/gargantext-server
    ghc-options:
    - -O2
    - -Wcompat
    - -Wmissing-signatures
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -fprof-auto
    dependencies:
      - base
      - containers
      - gargantext
      - vector
      - cassava
      - ini
      - optparse-generic
      - unordered-containers
      - full-text-search

  gargantext-cli:
    main: Main.hs
    source-dirs: bin/gargantext-cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - aeson
      - async
      - base
      - bytestring
      - containers
      - gargantext
      - vector
      - cassava
      - ini
      - optparse-generic
      - split
      - unordered-containers
      - full-text-search

  gargantext-phylo:
    main: Main.hs
    source-dirs: bin/gargantext-phylo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - aeson
      - async
      - base
      - bytestring
      - containers
      - directory
      - gargantext
      - vector
      - parallel
      - cassava
      - ini
      - optparse-generic
      - split
      - unordered-containers

  gargantext-adaptative-phylo:
    main: Main.hs
    source-dirs: bin/gargantext-adaptative-phylo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - aeson
      - async
      - base
      - bytestring
      - containers
      - directory
      - gargantext
      - vector
      - parallel
      - cassava
      - ini
      - optparse-generic
      - split
      - unordered-containers      

  gargantext-import:
    main: Main.hs
    source-dirs: bin/gargantext-import
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - gargantext
      - base
      - servant-server

  gargantext-init:
    main: Main.hs
    source-dirs: bin/gargantext-init
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - gargantext
      - base

  gargantext-cbor2json:
    main: Main.hs
    source-dirs: bin/gargantext-cbor2json
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - gargantext
      - base
      - bytestring
      - aeson
      - serialise


tests:
   garg-test:
     main: Main.hs
     source-dirs: src-test
     default-extensions:
     - DataKinds
     - DeriveGeneric
     - FlexibleContexts
     - FlexibleInstances
     - GeneralizedNewtypeDeriving
     - MultiParamTypeClasses
     - NoImplicitPrelude
     - OverloadedStrings
     - RankNTypes
     ghc-options:
     - -threaded
     - -rtsopts
     - -with-rtsopts=-N
     dependencies:
     - base
     - gargantext
     - hspec
     - QuickCheck
     - quickcheck-instances
     - time
     - parsec
     - duckling
     - text
#  garg-doctest:
#    main: Main.hs
#    source-dirs: src-doctest
#    ghc-options:
#    - -O2
#    - -Wcompat
#    - -Wmissing-signatures
#    - -rtsopts
#    - -threaded
#    - -with-rtsopts=-N
#    dependencies:
#    - doctest
#    - Glob
#    - QuickCheck
#    - base
#    - gargantext
#    default-extensions:
#    - DataKinds
#    - DeriveGeneric
#    - FlexibleContexts
#    - FlexibleInstances
#    - GeneralizedNewtypeDeriving
#    - MultiParamTypeClasses
#    - NoImplicitPrelude
#    - OverloadedStrings
#    - RankNTypes
#

