flags: {}
extra-package-dbs: []
packages:
- .
#- /home/alexandre/local/logiciels/haskell/servant/servant-multipart
#- /home/alexandre/local/logiciels/haskell/utc
extra-deps:
- aeson-1.0.2.1
- duckling-0.1.3.0
- protolude-0.2
- servant-multipart-0.10.0.1
resolver: lts-9.2
