resolver: lts-12.10
flags: {}
extra-package-dbs: []
packages:
- .
- 'deps/servant-job'
- 'deps/clustering-louvain'
  #- 'deps/imt-api-client'

allow-newer: true
extra-deps:
- git: https://github.com/delanoe/data-time-segment.git
  commit: 4e3d57d80e9dfe6624c8eeaa8595fc8fe64d8723
- git: https://gitlab.iscpif.fr/gargantext/hlcm.git
  commit: 6f0595d2421005837d59151a8b26eee83ebb67b5
- git: https://github.com/delanoe/servant-static-th.git
  commit: ba5347e7d8a13ce5275af8470c15b2305fbb23af
- accelerate-1.2.0.0
- opaleye-0.6.7002.0
- aeson-lens-0.5.0.0
- duckling-0.1.3.0
- full-text-search-0.2.1.4
- fullstop-0.1.4
- probable-0.1.3
- rake-0.0.1
- located-base-0.1.1.1
- servant-multipart-0.11.2
- stemmer-0.5.2
- servant-flatten-0.2
- serialise-0.2.0.0  # imt-api-client
- KMP-0.1.0.2
