flags: {}
extra-package-dbs: []
packages:
- .
allow-newer: true
extra-deps:
- git: https://github.com/delanoe/data-time-segment.git
  commit: 4e3d57d80e9dfe6624c8eeaa8595fc8fe64d8723
- aeson-0.11.3.0
- aeson-lens-0.5.0.0
- duckling-0.1.3.0
- extra-1.5.3
- haskell-src-exts-1.18.2
- http-types-0.12.1
- protolude-0.2
- servant-0.12.1
- servant-auth-0.3.0.1
- servant-client-0.12.0.1
- servant-client-core-0.12
- servant-docs-0.11.1
- servant-multipart-0.11.1
- servant-server-0.12
- text-1.2.3.0
- text-show-3.6.2
resolver: lts-10.6
