flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- aeson-1.0.2.1
- attoparsec-0.13.2.2
- duckling-0.1.3.0
- http-media-0.7.1.2
- http-types-0.11
- mmorph-1.1.0
- protolude-0.2
- servant-0.12.1
- servant-auth-0.3.0.1
- servant-client-0.12.0.1
- servant-client-core-0.12
- servant-docs-0.11.1
- servant-mock-0.8.3
- servant-multipart-0.11.1
- servant-server-0.12
- text-1.2.3.0
resolver: lts-9.2
