flags: {}
extra-package-dbs: []
packages:
- .
- servant-job
- clustering-louvain

allow-newer: true
extra-deps:
- git: https://github.com/delanoe/data-time-segment.git
  commit: 4e3d57d80e9dfe6624c8eeaa8595fc8fe64d8723
- git: https://gitlab.iscpif.fr/gargantext/hlcm.git
  commit: 6f0595d2421005837d59151a8b26eee83ebb67b5
- git: https://github.com/delanoe/servant-static-th.git
  commit: fff77e79fe94d563ab5cae2609b78c17b5c1f434
  #- git: https://github.com/delanoe/accelerate.git
  #commit: 007fd483a4410441fb5dd1b689a5f7dab66d27ad
- accelerate-1.2.0.0
- aeson-1.2.4.0
- aeson-lens-0.5.0.0
- duckling-0.1.3.0
- extra-1.5.3
- full-text-search-0.2.1.4
- fullstop-0.1.4
- haskell-src-exts-1.18.2
- http-types-0.12.1
- protolude-0.2
- servant-0.13
- servant-auth-0.3.0.1
- servant-client-0.13
- servant-client-core-0.13
- servant-docs-0.11.1
- servant-multipart-0.11.1
- servant-server-0.13
- servant-swagger-ui-0.2.3.2.2.8
- stemmer-0.5.2
- text-1.2.3.0
- text-show-3.6.2
- servant-flatten-0.2
resolver: lts-11.10
