version: '3'

services:
  postgres:
    image: 'postgres:latest'
    network_mode: host
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: gargantua
      POSTGRES_PASSWORD: C8kdcUrAQy66U
      POSTGRES_DB: gargandbV5
    volumes:
      - garg-pgdata:/var/lib/postgresql/data
      - ../:/gargantext
      - ../dbs:/dbs
      - ../postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: admin

    depends_on:
      - postgres
    links:
      - postgres

  corenlp:
    image: 'cgenie/corenlp-garg'
    ports:
      - 9000:9000

volumes:
  garg-pgdata:
